### ISSUE TITLE
Current version of RDBMS is not supported.

### ISSUE THREAD

**Issue by jorgb90** [magenx/Magento-2-server-installation#232]
Just installed a new server with MagenX but when running setup:upgrade I am getting the following error:

`Current version of RDBMS is not supported. Used Version: 10.11.7-MariaDB-1:10.11.7+maria~ubu2204. Supported versions: MySQL-8, MySQL-5.7, MariaDB-(10.2-10.6)`

I changed app/etc/di/xml into 10.11 but then I am getting the following error:

`Warning: preg_match(): Compilation failed: range out of order in character class at offset 25 in /home/xxx/public_html/vendor/magento/framework/DB/Adapter/SqlVersionProvider.php on line 101`

You also change this file to make it compatible with MariaDB 10.11?

**Comment by makproductions** [comment]
Hey @jorgb90 

A workaround for this issue is to modify the di.xml file and change the MARIADB requirements. 

`<item name="MariaDB-(10.2-10.6)" xsi:type="string">^10\.[2-6]\.</item>`
TO:
`<item name="MariaDB-(10.2-10.6)" xsi:type="string">^10</item>`

Again, a temporary work around. Ive been using magento with the latest version of mariadb and have not had issues. Hope it helps

**Comment by jorgb90** [comment]
@makproductions Thanks, but I did this as you can read, because that worked before but MagenX script is now installing MariaDB 10.11

**Comment by artmouse** [comment]
@jorgb90 https://github.com/Sental/db-override

**Comment by jorgb90** [comment]
@artmouse 

Thanks! Module also only alters the di.xml but I think I must have done something wrong myself, cause through the module its working and not complaining further.

**Comment by musabatas** [comment]
`<item name="MariaDB-10.x" xsi:type="string">^10.\d{1,2}.</item>`
